apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - mysql-pvc.yaml
  - wordpress-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - wordpress-deployment.yaml
  - wordpress-service.yaml
